export type Relationship = "manager" | "coworker" | "report";

export interface Score {
  value: number;
  attribute: string;
}

export interface Dot {
  id: number;
  reviewer: string;
  title: string;
  relationship: Relationship;
  date: string;
  text: string;
  scores: Score[];
  topic?: string;
}

export const dots: Dot[] = [
  {
    id: 1,
    reviewer: "Reviewer 3",
    title: "Senior Software Engineer",
    relationship: "coworker",
    date: "07/31/2026",
    text: `"better to burn than talk about it when theres 100 things to burn". Glad you're back`,
    scores: [{ value: 8, attribute: "Cut through it" }],
  },
  {
    id: 2,
    reviewer: "Reviewer 18",
    title: "Architect",
    relationship: "coworker",
    date: "07/23/2026",
    text: "appreciate your rawness.",
    scores: [{ value: 8, attribute: "Ran the meritocracy" }],
  },
  {
    id: 3,
    reviewer: "Reviewer 6",
    title: "Senior Software Engineer",
    relationship: "report",
    date: "06/08/2026",
    text: `I think you've done an exceptional job leading the team and delivering an incredible product in PAT. You've got a very strong sense about the product, what makes a good product, including not just the tech implementation, but also things like what good engagement with the customer base looks like. You've owned it top to bottom, and that's really cool. You've also done a really good job with motivating the team, establishing a culture of innovation and entrepreneurship, cutting thru, making quick loops, etc, which I think is key in the FDE space, and I think is a key reason PAT has been such a success. Culturally, and as a leader, I have seen you repeatedly seek open and honest feedback, and reach out to me multiple times to make sure I am doing well, that my morale is good, etc etc.\n\nIn terms of areas for growth:\n\n1. I think as a tech lead, you can level up your effectiveness by being plugged in more with what's happening in the broader organization, and who you can go to for help with various things. An example that comes to mind is around the CI/CD pipelines, where it felt like we were kind of stuck, until we finally talked with ████████.\n\n2. You have a very strong sense of how things should be, which is a key strength, and I don't want that to be lost. But I worry that sometimes you're holding on to the principled view of what you think good looks like a little too strongly, at the expense of practical considerations. An example of this was working thru the performance and delorean branching strategy work, where I think it took a lot to convince you to go ahead with the change. I think you had really good concerns, that led us to a net better place, but I think the process was bumpier than it needed to be.`,
    scores: [
      { value: 10, attribute: "Acted like an owner" },
      { value: 5, attribute: "Disagreed productively" },
      { value: 8, attribute: "Handled pressure" },
      { value: 10, attribute: "Welcomed feedback" },
      { value: 8, attribute: "Designed conceptual/practical architecture" },
      { value: 8, attribute: "Cared for others" },
      { value: 8, attribute: "Built the path to the vision" },
      { value: 8, attribute: "Created clarity" },
      { value: 8, attribute: "Understood business requirements" },
      { value: 8, attribute: "Led an effective team" },
    ],
    topic: "2026 Mid-Year Reviews",
  },
  {
    id: 4,
    reviewer: "Reviewer 3",
    title: "Senior Software Engineer",
    relationship: "coworker",
    date: "06/08/2026",
    text: `PAT. Enough said.\n\nBut to say a little more — you excelled this period in a few key areas. (1) getting it done — you picked your bets, fought your battles, and (mostly) avoided getting bogged down in bureaucracy. I'd take that bet 10/10 times, especially in the FDE space, but should note that it came at the cost of your own time/sleep, cross-team dependency bumpiness, and some management friction — all areas you can improve. (2) Your focus on keeping folks motivated and unblocked, especially newcomers like ██████ — don't lose that, although for your own sake consider how much of a shield you need to be for your team. It was a genuine joy to build PAT with you. (3) Cultural engagement — you are relentlessly open to feedback and self improvement and provide excellent feedback to others up-and-down.\n\nYou stretched across many different dimensions this period. Which excite you the most? What focus is sustainable for you in the long term?`,
    scores: [
      { value: 4, attribute: "Escalated" },
      { value: 9, attribute: "Cared for others" },
      { value: 5, attribute: "Orchestrated people and processes effectively" },
      { value: 9, attribute: "Delivered results" },
      { value: 9, attribute: "Acted like an owner" },
    ],
    topic: "2026 Mid-Year Reviews",
  },
  {
    id: 5,
    reviewer: "Santi Weight",
    title: "Senior Software Engineer",
    relationship: "coworker",
    date: "06/05/2026",
    text: `self grade: above\n\nPAT went very well and we delivered a tough product that people love. all in all, im very happy with how things went. lots learned and excited to do better next time.`,
    scores: [{ value: 7, attribute: "Delivered results" }],
    topic: "2026 Mid-Year Reviews",
  },
  {
    id: 6,
    reviewer: "Reviewer 19",
    title: "Senior QA Engineer",
    relationship: "report",
    date: "06/05/2026",
    text: `PAT would not be where it is today without you leading it. No two ways about it. You had laser focus on delivery and looping. You didn't tolerate slow iterations or blockers and came up with creative workaround everytime to ensure the flow is never disturbed. On the technical side as well, you effortlessly stood a complex product like PAT in no time with agentic workflows, evals, custom delivery mechanism, integrating with external teams (e.g. Delorean search), etc. Sheer hours you put in to achieve this is admirable.\n\nConstructively though, there was some noise around xteam dependencies (delorean search, pixi/uv, gitlab, getting more resources, etc.), target state architecture (service based or local, delorean storage, etc.). Seemed like you were trying to fight all those battles by yourself vs leveraging others or escalating to get more help.`,
    scores: [
      { value: 9, attribute: "Delivered results" },
      { value: 8, attribute: "Was creative" },
      { value: 9, attribute: "Took the bull by the horns" },
      { value: 8, attribute: "Motivated others" },
      { value: 8, attribute: "Led an effective team" },
      { value: 3, attribute: "Escalated" },
      { value: 8, attribute: "Acted like an owner" },
      { value: 5, attribute: "Collaborated effectively" },
      { value: 8, attribute: "Designed conceptual/practical architecture" },
      { value: 7, attribute: "Handled pressure" },
      { value: 8, attribute: "Didn't tolerate a problem" },
    ],
    topic: "2026 Mid-Year Reviews",
  },
  {
    id: 7,
    reviewer: "Reviewer 20",
    title: "Tech Lead",
    relationship: "coworker",
    date: "05/26/2026",
    text: "Absolutely excellent PAT demo at the LangChain Interrupt conference. It's a rare demo that captures an audience from the beginning, and doesn't let go throughout — but you guys managed!",
    scores: [
      { value: 9, attribute: "Accurately represented Bridgewater" },
      { value: 9, attribute: "Strove for excellence & high standards" },
      { value: 9, attribute: "Communicated clearly" },
    ],
  },
  {
    id: 8,
    reviewer: "Reviewer 21",
    title: "Senior Investment Associate",
    relationship: "coworker",
    date: "05/21/2026",
    text: "Really great presentation at LangChain — came across as very compelling / impressive!",
    scores: [{ value: 9, attribute: "Accurately represented Bridgewater" }],
  },
  {
    id: 9,
    reviewer: "Reviewer 3",
    title: "Senior Software Engineer",
    relationship: "coworker",
    date: "05/21/2026",
    text: "LangChain PAT presentation — nice job! Clear & compelling across multiple levels; packed a lot of good detail into a pretty short talk.",
    scores: [
      { value: 8, attribute: "Accurately represented Bridgewater" },
      { value: 8, attribute: "Communicated clearly" },
    ],
  },
  {
    id: 10,
    reviewer: "Reviewer 22",
    title: "Architect",
    relationship: "coworker",
    date: "05/21/2026",
    text: "LangChain talk on Pocket Analyst — great work!",
    scores: [
      { value: 8, attribute: "Communicated clearly" },
      { value: 9, attribute: "Accurately represented Bridgewater" },
      { value: 8, attribute: "Displayed understanding of investment subject matter" },
    ],
  },
  {
    id: 11,
    reviewer: "Reviewer 8",
    title: "Engineering Manager",
    relationship: "manager",
    date: "05/08/2026",
    text: "Thank you both for your time (it was quite an investment) this week on on boarding the team. We will likely continue to lean on you for a while, but you are always willing and available. Doesn't go unnoticed.",
    scores: [
      { value: 8, attribute: "Collaborated effectively" },
      { value: 8, attribute: "Developed others" },
    ],
  },
  {
    id: 12,
    reviewer: "Reviewer 15",
    title: "Chief of Staff",
    relationship: "coworker",
    date: "05/05/2026",
    text: "yesterday — appreciate that you were game from the start and made it happen",
    scores: [
      { value: 8, attribute: "Built community" },
      { value: 8, attribute: "Cared for others" },
    ],
  },
  {
    id: 13,
    reviewer: "Reviewer 9",
    title: "Senior Back End Software Engineer",
    relationship: "coworker",
    date: "05/05/2026",
    text: "Good demo in the prod eng meeting, generating code for the whole graph in parallel with defined interfaces was a very interesting detail and a potential design pattern to learn from",
    scores: [
      { value: 8, attribute: "Designed conceptual/practical architecture" },
      { value: 7, attribute: "Developed others" },
    ],
  },
  {
    id: 14,
    reviewer: "Reviewer 1",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "05/05/2026",
    text: "The last few days. Always saying and doing the hard things",
    scores: [{ value: 8, attribute: "Led by example" }],
  },
  {
    id: 15,
    reviewer: "Reviewer 6",
    title: "Senior Software Engineer",
    relationship: "report",
    date: "04/29/2026",
    text: "very belated dot, but pushing for open beta vs GA, and getting in sync on expectations post first release",
    scores: [
      { value: 8, attribute: "Displayed courage" },
      { value: 8, attribute: "Managed risk" },
      { value: 8, attribute: "Created clarity" },
    ],
  },
  {
    id: 16,
    reviewer: "Reviewer 6",
    title: "Senior Software Engineer",
    relationship: "report",
    date: "04/29/2026",
    text: "checking in on morale, recognizing the hard work, encouraging me to take time off if needed",
    scores: [
      { value: 10, attribute: "Motivated others" },
      { value: 10, attribute: "Cared for others" },
    ],
  },
  {
    id: 17,
    reviewer: "Reviewer 16",
    title: "Senior Software Engineer",
    relationship: "coworker",
    date: "04/16/2026",
    text: "good job letting ████ make the case for his vision and trusting him",
    scores: [{ value: 8, attribute: "Led an effective team" }],
  },
  {
    id: 18,
    reviewer: "Reviewer 3",
    title: "Senior Software Engineer",
    relationship: "coworker",
    date: "04/13/2026",
    text: "Dotting from weekly retro — you've been on top of user feedback and issues both in slack and all over the office; great hands-on interaction to both solve problems and build connection with people. Definitely don't stop doing this, but we can compound this and prevent both burnout and key-person risk by doing a little more runbooking",
    scores: [
      { value: 8, attribute: "Didn't tolerate a problem" },
      { value: 8, attribute: "Strove for excellence & high standards" },
    ],
  },
  {
    id: 19,
    reviewer: "Reviewer 17",
    title: "Investment Associate",
    relationship: "coworker",
    date: "04/09/2026",
    text: "PAT Support this week.",
    scores: [{ value: 7, attribute: "Didn't tolerate a problem" }],
  },
  {
    id: 20,
    reviewer: "Reviewer 1",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "04/07/2026",
    text: "Great team event last week, thanks for organizing",
    scores: [{ value: 8, attribute: "Built community" }],
  },
  {
    id: 21,
    reviewer: "Reviewer 1",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "04/07/2026",
    text: "Pushing for what you believe on for DGame access in workspaces. And with broader vision for why you're doing the thing you're doing.",
    scores: [
      { value: 8, attribute: "Led by example" },
      { value: 8, attribute: "Strategized" },
    ],
  },
  {
    id: 22,
    reviewer: "Reviewer 10",
    title: "Senior Software Engineer",
    relationship: "coworker",
    date: "04/06/2026",
    text: "Slack thread today about D-Game changes. It was kind of a mess of a message. Didn't do a good job of communicating what you were looking for. In the specifics it was hard to engage on what you sent. Think you were pushing forward on writing code without thinking about how that fits into a broader picture and what it means to land a change of this sort well. Missing basic things like a design which would help you on both fronts as minimally an artifact to get people in sync with on your goals, approach, etc.",
    scores: [
      { value: 3, attribute: "Designed conceptual/practical architecture" },
      { value: 3, attribute: "Synthesized the situation" },
      { value: 3, attribute: "Built the path to the vision" },
      { value: 8, attribute: "Listened well" },
    ],
  },
  {
    id: 23,
    reviewer: "Reviewer 3",
    title: "Senior Software Engineer",
    relationship: "coworker",
    date: "04/06/2026",
    text: "Awe in AE — thanks for organizing!",
    scores: [{ value: 8, attribute: "Built community" }],
  },
  {
    id: 24,
    reviewer: "Reviewer 4",
    title: "Product Manager",
    relationship: "coworker",
    date: "04/03/2026",
    text: "Awe in AE event was excellent — thank you",
    scores: [{ value: 9, attribute: "Built community" }],
  },
  {
    id: 25,
    reviewer: "Reviewer 5",
    title: "Tech Lead",
    relationship: "manager",
    date: "04/02/2026",
    text: "PAT to GA",
    scores: [
      { value: 10, attribute: "Delivered results" },
      { value: 10, attribute: "Acted like an owner" },
    ],
  },
  {
    id: 26,
    reviewer: "Reviewer 7",
    title: "Very Senior Investment Person",
    relationship: "manager",
    date: "03/28/2026",
    text: "Belated but PAT is / is going to be transformational for hwdw. Well done!",
    scores: [{ value: 10, attribute: "Delivered results" }],
  },
  {
    id: 27,
    reviewer: "Reviewer 4",
    title: "Product Manager",
    relationship: "coworker",
    date: "03/25/2026",
    text: `Re todays PAT-Security Go-NoGo: I think that session was really WGLL — Ive attended many meetings like this, and this one felt significantly smoother. The level of ownership and thoughtfulness came across clearly in the room. To call out a few specifics — your writeup was detailed and literally had answers to anything that popped in that meeting. The effort you put in to prep for the meeting and generate that page proves that you arent treating security signoff as an annoyance, but rather an issue you care about and want to serve as a real thought-partner. Lastly, I think good job communicating clearly and always ending with "so I am hearing a Yes on this one, correct?" Dont think anyone left the room unsure about the decision. Good work`,
    scores: [
      { value: 10, attribute: "Collaborated effectively" },
      { value: 10, attribute: "Displayed skill & experience" },
    ],
  },
  {
    id: 28,
    reviewer: "Reviewer 2",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "03/25/2026",
    text: "Great job in security meeting. Clear you did lots of prep and thought you communicated very clearly",
    scores: [{ value: 8, attribute: "Managed risk" }],
  },
  {
    id: 29,
    reviewer: "Reviewer 14",
    title: "Senior Investment Associate",
    relationship: "coworker",
    date: "03/18/2026",
    text: "██████ and I basically did an entire IC writeup's worth of analysis almost entirely in PAT this week. the new version is really a game changer and massive step up vs before. amazing stuff, great work",
    scores: [{ value: 10, attribute: "Systematized investment understanding" }],
  },
  {
    id: 30,
    reviewer: "Reviewer 1",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "03/18/2026",
    text: "Proud of you two for showcasing your work today. Really well done.",
    scores: [{ value: 8, attribute: "Communicated clearly" }],
  },
  {
    id: 31,
    reviewer: "Reviewer 1",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "03/18/2026",
    text: "Pretty incredible work getting us to where we are today with PAT. Blown away by how far this has come from where we started thanks to all of you...",
    scores: [
      { value: 10, attribute: "Shaped change" },
      { value: 10, attribute: "Delivered results" },
    ],
  },
  {
    id: 32,
    reviewer: "Reviewer 1",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "03/13/2026",
    text: "Seeing a hugely renewed version of you this week. So on your game, guiding the PAT team well.\n\nAnd as always, excellent reflections in our conversations.",
    scores: [
      { value: 8, attribute: "Displayed skill & experience" },
      { value: 8, attribute: "Led an effective team" },
    ],
  },
  {
    id: 33,
    reviewer: "Reviewer 2",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "03/13/2026",
    text: "Great stuff this week. Really on top of everything (code reviews, logistics w external teams, CI, product stuff, etc). Huge spike up on the intensity and proactiveness over the past week or two. Love to see it, and it's what we'll need to maximize PAT's potential",
    scores: [
      { value: 8, attribute: "Orchestrated people and processes effectively" },
      { value: 8, attribute: "Delivered results" },
    ],
  },
  {
    id: 34,
    reviewer: "Reviewer 1",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "02/19/2026",
    text: "setting up speakeasy magick team event — thanks for organizing",
    scores: [{ value: 9, attribute: "Built community" }],
  },
  {
    id: 35,
    reviewer: "Reviewer 11",
    title: "Very Senior Tech Person",
    relationship: "manager",
    date: "02/12/2026",
    text: `"I'm not personally entertaining it" is not an acceptable answer to anyone who is trying to help you. Try "That seems like a horrible suggestion, why do you think it's reasonable?" or something similar. Dismissing and not engaging is not going to work.`,
    scores: [
      { value: 1, attribute: "Used strong logic" },
      { value: 1, attribute: "Knew what you didn't know and what to do about it" },
      { value: 1, attribute: "Listened well" },
    ],
  },
  {
    id: 36,
    reviewer: "Reviewer 12",
    title: "Senior Software Engineer",
    relationship: "coworker",
    date: "02/11/2026",
    text: "tight collaboration on storage interface. easy to rapidly engage with you and get the context i need\n\nseparate story on how looping on that design is going but that's not entirely relevant to you",
    scores: [{ value: 8, attribute: "Collaborated effectively" }],
  },
  {
    id: 37,
    reviewer: "Reviewer 8",
    title: "Engineering Manager",
    relationship: "manager",
    date: "02/11/2026",
    text: "PAT newsletter",
    scores: [{ value: 8, attribute: "Shaped change" }],
  },
  {
    id: 38,
    reviewer: "Reviewer 9",
    title: "Senior Back End Software Engineer",
    relationship: "coworker",
    date: "02/10/2026",
    text: `Good advice in the FDE All hands around nuking the code, I haven't been doing that enough and keep running into reshaping slowly as much as possible with painfully slow rate of success.\n\nMaybe I should try the 're-write + delete method' part by part instead.`,
    scores: [{ value: 7, attribute: "Advised wisely" }],
  },
  {
    id: 39,
    reviewer: "Reviewer 11",
    title: "Very Senior Tech Person",
    relationship: "manager",
    date: "02/06/2026",
    text: "Your PAT GA document and kickoff meeting were excellent. The doc was comprehensive and your participation in the meeting was motivating and unifying.",
    scores: [
      { value: 7, attribute: "Communicated clearly" },
      { value: 7, attribute: "Built a big tent/was inclusive" },
      { value: 7, attribute: "Collaborated effectively" },
    ],
  },
  {
    id: 40,
    reviewer: "Reviewer 11",
    title: "Very Senior Tech Person",
    relationship: "manager",
    date: "02/06/2026",
    text: "Your engagement on PAT resourcing needs over the past two weeks was below the bar on several fronts. I need you to synthesize your team's needs clearly and consistently, manage communications in coordination with others (██████/██████), and proactively pull me in when you need help. We spoke about these issues and I think you're making clear changes on some of these.",
    scores: [
      { value: 7, attribute: "Perceived a problem" },
      { value: 3, attribute: "Synthesized the situation" },
      { value: 3, attribute: "Collaborated effectively" },
      { value: 3, attribute: "Knew what you didn't know and what to do about it" },
    ],
  },
  {
    id: 41,
    reviewer: "Reviewer 6",
    title: "Senior Software Engineer",
    relationship: "report",
    date: "02/04/2026",
    text: "There's a buzz in the air and a vibrancy to the team, that feels exciting and like a breath of fresh air, and it seems to start with the two of you",
    scores: [
      { value: 10, attribute: "Led an effective team" },
      { value: 10, attribute: "Motivated others" },
    ],
  },
  {
    id: 42,
    reviewer: "Reviewer 6",
    title: "Senior Software Engineer",
    relationship: "report",
    date: "02/04/2026",
    text: "Actively seeking and encouraging feedback. It feels empowering",
    scores: [
      { value: 8, attribute: "Welcomed feedback" },
      { value: 8, attribute: "Led by example" },
    ],
  },
  {
    id: 43,
    reviewer: "Reviewer 13",
    title: "Tech Lead",
    relationship: "coworker",
    date: "02/02/2026",
    text: "In the future I would appreciate it if you gave me the opportunity to talk to my resources about any changes in their responsibilities before making announcements about it in public channels",
    scores: [{ value: 5, attribute: "Collaborated effectively" }],
  },
  {
    id: 44,
    reviewer: "Reviewer 11b",
    title: "Architect",
    relationship: "coworker",
    date: "02/02/2026",
    text: "Quick call / check in today",
    scores: [
      { value: 8, attribute: "Cared for others" },
      { value: 8, attribute: "Collaborated effectively" },
    ],
  },
  {
    id: 45,
    reviewer: "Reviewer 3",
    title: "Senior Software Engineer",
    relationship: "coworker",
    date: "01/30/2026",
    text: "Appreciate your thinking on retro items and reflections on recent frustration — it's helpful to hear when I'm not in every conversation",
    scores: [{ value: 8, attribute: "Was radically transparent" }],
  },
  {
    id: 46,
    reviewer: "Reviewer 1",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "01/28/2026",
    text: "Good (unprompted) reflectiveness this morning. You do this better than many; I think it's why you're looping / evolving so fast.",
    scores: [{ value: 8, attribute: "Improved/Grew" }],
  },
  {
    id: 47,
    reviewer: "Reviewer 3",
    title: "Senior Software Engineer",
    relationship: "coworker",
    date: "01/21/2026",
    text: "As discussed live after PAT GA plan meeting with tech, I think you had a slight miss in setting the goal and making sure key folks had the right context/frame of mind before jumping into specifics. Still achieved the meeting goal and live discussion was great, so this is mostly on the margins.",
    scores: [
      { value: 7, attribute: "Communicated clearly" },
      { value: 5, attribute: "Proactively anticipated needs" },
    ],
  },
  {
    id: 48,
    reviewer: "Reviewer 8",
    title: "Engineering Manager",
    relationship: "manager",
    date: "12/29/2025",
    text: `#2025Reviews\n\nAbove expectations for the year. Strong first half in the platform space with the logic model being a key win. Switch to the AI team was another fruitful change — Code Assist really demonstrated solid delivery but more importantly excellent engagement with users. Lots of little but meaningful wins (testing framework as an example) throughout the course of the summer. With PAT, showed great entrepreneurial skills — leading and engaged in all aspects of the project.\n\nOver the next year, plenty of room (and potential) to grow. How to actually take PAT from a prototype to an actual product will be challenging and the associated complexities will be new. Can also be more effective by managing emotions, especially frustrations, better. Excellent at taking feedback, internalizing and looping but in the moment it shows and at times erodes collaborative nature.`,
    scores: [
      { value: 8, attribute: "Developed code" },
      { value: 9, attribute: "Displayed skill & experience" },
      { value: 9, attribute: "Led by example" },
      { value: 4, attribute: "Disagreed productively" },
      { value: 8, attribute: "Shaped change" },
      { value: 9, attribute: "Delivered results" },
    ],
    topic: "Tech EOY Reviews 2025",
  },
  {
    id: 49,
    reviewer: "Reviewer 4",
    title: "Product Manager",
    relationship: "coworker",
    date: "12/19/2025",
    text: "Pre holidays team win slack message",
    scores: [{ value: 8, attribute: "Motivated others" }],
  },
  {
    id: 50,
    reviewer: "Reviewer 4",
    title: "Product Manager",
    relationship: "coworker",
    date: "12/19/2025",
    text: `PAT UAT war room: Good job (as with last time) setting it up and achieving the goal of us all getting deep into the next version of PAT. However, surprised that the ad-hoc session later that was framed in Slack as a "technical React handoff" was actually a feature/bug prioritization session — if ████████ hadn't messaged me to join I would have missed that. Reminder that such convos should be in a team setting and not in a sub group silo.`,
    scores: [
      { value: 4, attribute: "Collaborated effectively" },
      { value: 8, attribute: "Led an effective team" },
    ],
  },
  {
    id: 51,
    reviewer: "Reviewer 3",
    title: "Senior Software Engineer",
    relationship: "coworker",
    date: "12/18/2025",
    text: "Productive PAT React war room — good problem perceptions and user-empathetic feedback",
    scores: [
      { value: 7, attribute: "Understood business requirements" },
      { value: 8, attribute: "Perceived a problem" },
      { value: 7, attribute: "Tested software/solution" },
    ],
  },
  {
    id: 52,
    reviewer: "Reviewer 1",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "12/11/2025",
    text: "Escalating for what you need is excellent.",
    scores: [{ value: 8, attribute: "Escalated" }],
  },
  {
    id: 53,
    reviewer: "Reviewer 1",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "12/11/2025",
    text: "Problem perception and raising it well.",
    scores: [{ value: 8, attribute: "Perceived a problem" }],
  },
  {
    id: 54,
    reviewer: "Reviewer 2",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "12/03/2025",
    text: "Good feedback on recent large MR. Not per se complimenting the feedback (although it was good), but more so want to call it out that it shows you are really engaging with the changes and not letting things slip through the cracks. Good balance of knowing when to get in the weeds and when not to (and I think it's a good habit you have of asking what does / doesn't require deep review from you)",
    scores: [
      { value: 8, attribute: "Acted like an owner" },
      { value: 8, attribute: "Displayed skill & experience" },
    ],
  },
  {
    id: 55,
    reviewer: "Reviewer 2",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "11/24/2025",
    text: `great feedback this am. incredibly helpful for my development and appreciate you both forcing the more "uncomfortable" conversations + putting me on spot`,
    scores: [{ value: 8, attribute: "Gave useful feedback" }],
  },
  {
    id: 56,
    reviewer: "Reviewer 1",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "11/24/2025",
    text: "In general, you're encouraging discourse and debate on the team in a really good way. Good mental maps re: getting the team in sync on a nubby issue this morning; spending more time to get in sync is always the right call.",
    scores: [{ value: 8, attribute: "Led an effective team" }],
  },
  {
    id: 57,
    reviewer: "Reviewer 4",
    title: "Product Manager",
    relationship: "coworker",
    date: "11/21/2025",
    text: "Good push in today's team session to recognize the wins and progress from the recent period",
    scores: [{ value: 9, attribute: "Motivated others" }],
  },
  {
    id: 58,
    reviewer: "Reviewer 11b",
    title: "Architect",
    relationship: "coworker",
    date: "11/19/2025",
    text: "demo & technical walk through yesterday!",
    scores: [{ value: 8, attribute: "Synthesized the situation" }],
  },
  {
    id: 59,
    reviewer: "Reviewer 1",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "10/27/2025",
    text: `One of the most talented engineers that I've ever had the pleasure of working with at BW. It was clear that he was very good when I worked with him on Plaid; but it was only this past period when he came to work on the Pocket Analyst (PAT) on the AE Core AI team that it became clear the degree to which he is a superstar.\n\nHis superpower is a combination of ownership, creativity, and intense focus on delivery that enables him to quickly grasp the goals that we want to go after, ideate and ruthlessly prioritize the potential paths to get there, and then actually get after it — first individually (in an architect and SWE role) and then over the last month as the Technical Lead for the PAT project. On top of this, one of the better culture fits that I've seen come out of Technology (always says what's on his mind, is excellent at giving and receiving critical feedback) that more folks from Tech could model their behavior after. And always creates a consistently positive environment for our team. I can honestly say that we would not have been able to get as far as we have gotten on PAT without you. Thank you.\n\nThe clear areas of growth over the last few months have been with ability to lead, maintain composure while not losing any of the other attributes that make him great. I reflect on some of the challenges that we had to work through in July, how I've seen him work through similar challenges (at a broader scale) in the last 1-2 months and the difference is huge. Able to handle significantly more pressure, react much more thoughtfully than before. And a lot of this growth I attribute to the fact that he is so open and able to take feedback (and loop on it) as well as he does.\n\nThe main areas to improve on are:\n\n— Communication. There are often times where we'll hit a situation where either (a) misunderstanding a question that's been asked or (b) appearing to be in disagreement in a conversation over a particular set of words (when in reality, there isn't actually a disagreement). Communication is obviously a two-way street, but I think that there's probably more that could be done to just slow down, ask questions, push for clarification, push for "in-syncness" on terminology.\n\n— Connection to business, how we do work. I think that there's still a pretty material gap in terms of understanding how we do work that needs to close to have even more impact. There's a lot of context that folks like myself, ████████ have that is needed for informing the direction of certain aspects of these types of projects. If able to develop this "taste" by getting closer to how our research process works, how our systems are architected, I think that it could be hugely unlocking.\n\n— Collaboration: Much smaller point. Collaboration is generally amazing. But I perceive there's a bit of a desire to play all of the roles — Lead, Architect, SWE, PdM, and even PjM at times. A lot of this happened earlier on, but I still see it happening in fits and starts at times. That can work that way (and almost has to work that way) when in the rapid experimentation phase early on in a project like ours. But I'm not sure that can really work as the project scales in the way that it has. Could do a better job of offloading, delegating (esp. some of the PdM/PjM types of responsibilities that he would occasionally try to take on when we already had a PdM).\n\nThe overwhelming takeaway here is that he is phenomenal. We wouldn't have gotten as far as we have on PAT without you. And we're only just getting started.`,
    scores: [
      { value: 9, attribute: "Shaped change" },
      { value: 9, attribute: "Took the bull by the horns" },
      { value: 10, attribute: "Displayed skill & experience" },
      { value: 8, attribute: "Disagreed productively" },
      { value: 10, attribute: "Delivered results" },
      { value: 9, attribute: "Was bluntly honest" },
      { value: 6, attribute: "Led an effective team" },
      { value: 7, attribute: "Understood business requirements" },
      { value: 7, attribute: "Collaborated effectively" },
      { value: 9, attribute: "Acted like an owner" },
      { value: 10, attribute: "Designed conceptual/practical architecture" },
      { value: 4, attribute: "Communicated clearly" },
    ],
    topic: "2025 EOY Reviews",
  },
  {
    id: 60,
    reviewer: "Reviewer 23",
    title: "Investment Associate",
    relationship: "coworker",
    date: "10/27/2025",
    text: "Lots of support during the PAT testing period and good tracking of themes to improve across meetings rather than just tracking the bugs. No outcomes for me to evaluate, since the tool wasn't very helpful at the stage it was during said period, but I hope the feedback was useful for you as a developer",
    scores: [{ value: 7, attribute: "Tested software/solution" }],
    topic: "2025 EOY Reviews",
  },
  {
    id: 61,
    reviewer: "Reviewer 4",
    title: "Product Manager",
    relationship: "coworker",
    date: "10/26/2025",
    text: `An absolute force in execution and a true dev force of nature. Ships high-quality code fast and shows deep understanding of both our architecture and AI enablement. In PAT, I have seen him step up as a vocal, thoughtful leader who sets clear goals for himself and the team and follows through. I think its fair to say the success of PAT is really attributed to your vision and work ethic, and the palpable passion you have to make this product a smash hit across every dimension. Partnership on input table prefilters and Code Assist has been excellent, and with the context developer crew has set a high bar for engagement, staying close to the work, responsive, and motivating. I also really value how receptive he is to feedback. Even when I have been direct about things that did not go well, takes it seriously and adjusts quickly, which says a lot about maturity and drive to improve.\n\nIf there is one area to keep working on, it is communication and framing. Sometimes the way things are worded can come off as a bit dismissive toward product or the broader tech org, even when that is not the intent. The "if I do not do it, no one will" mindset has been a big part of what makes him successful, but softening how that comes across in public channels would go a long way. I would also like to see him delegate and loop others in more. When we have sat down together to hash through PAT roadmaps or priorities, the sessions have been great, and I think they would be even better if he pulled me and others in earlier or more directly on areas we can help drive. Lastly, I would love to see more active instilling of his ethos and way of operating across others. Its not uncommon that I hear users saying "I wish we had more of him" and I can imagine a push on embedding your goodness in others being huge. That small shift would help scale impact even further.`,
    scores: [
      { value: 8, attribute: "Welcomed feedback" },
      { value: 10, attribute: "Delivered results" },
      { value: 5, attribute: "Developed others" },
      { value: 9, attribute: "Strove for excellence & high standards" },
      { value: 5, attribute: "Collaborated effectively" },
      { value: 9, attribute: "Acted like an owner" },
    ],
  },
  {
    id: 62,
    reviewer: "Reviewer 3",
    title: "Senior Software Engineer",
    relationship: "coworker",
    date: "10/24/2025",
    text: `This dot only reflects the last few weeks working on PAT. You're delivering rapidly while owning most of the architecture and planning; so far that has been successful. It's a level of ownership that's above what I saw when we last worked together on Plaid a year ago. You also bring a welcome enthusiasm to the team day in and day out; it's been great to work with you!\n\nI don't have much constructive feedback yet, but I'll say that so far, PAT has been a small team with a singular focus and few outside dependencies, so I look forward to seeing how you handle the challenges as that changes — a new stack, broader goals & ambiguity, and plugging in elsewhere in the FDE space.`,
    scores: [
      { value: 8, attribute: "Collaborated effectively" },
      { value: 7, attribute: "Led an effective team" },
      { value: 8, attribute: "Delivered results" },
    ],
  },
  {
    id: 63,
    reviewer: "Reviewer 2",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "10/24/2025",
    text: `This was my first time working with him, and man, he crushed it. What he did with PAT (and just as important, the speed at which he did it) was fun to see. Navigated the technical complexity of the ideas we were trying to spike out excellently. In addition to HoK work, stepped into the architect role quite nicely/naturally, and done a good job of ensuring we balance speed w/ quality and knows when its important to push on each of those attributes. Always eager to learn/try things out, and just overall a fun person to work with. The main piece of feedback I would have left had this been 2 months ago was that I think there's work to be done on balancing open-mindedness vs assertiveness (where you were sometimes overly assertive)... but the loops on that dimension have similarly been great. Calling it out partially because I think it's a thing we need to make sure keeps up, but mostly to just say the loops on your end have been noted.`,
    scores: [
      { value: 8, attribute: "Designed conceptual/practical architecture" },
      { value: 8, attribute: "Developed code" },
      { value: 8, attribute: "Delivered results" },
    ],
  },
  {
    id: 64,
    reviewer: "Reviewer 2",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "10/23/2025",
    text: "Great delivery over the past couple of weeks. Both from a speed and quality perspective — love it",
    scores: [
      { value: 8, attribute: "Delivered results" },
      { value: 8, attribute: "Strategized" },
    ],
  },
  {
    id: 65,
    reviewer: "Reviewer 3",
    title: "Senior Software Engineer",
    relationship: "coworker",
    date: "10/23/2025",
    text: "You've been a delivery machine during this push to PAT demo-complete, in terms of your own code delivery and running a pretty tight ship for planning, execution, and priority among different threads.",
    scores: [
      { value: 9, attribute: "Delivered results" },
      { value: 8, attribute: "Led an effective team" },
    ],
  },
  {
    id: 66,
    reviewer: "Reviewer 1",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "10/16/2025",
    text: "Pocket Analyst UX is so incredibly sleek now. So well done",
    scores: [{ value: 8, attribute: "Delivered results" }],
  },
  {
    id: 67,
    reviewer: "Reviewer 2",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "10/15/2025",
    text: "incredible job with the re-design of PAT (both UI and arch). still some small things to iron out, but this is so, so much better",
    scores: [
      { value: 10, attribute: "Designed conceptual/practical architecture" },
      { value: 10, attribute: "Delivered results" },
    ],
  },
  {
    id: 68,
    reviewer: "Reviewer 24",
    title: "Investment Associate",
    relationship: "coworker",
    date: "10/09/2025",
    text: "Just reflecting on initial experience with PaT, was impressed with the speed of iteration and voracity for honest feedback.",
    scores: [{ value: 9, attribute: "Collaborated effectively" }],
  },
  {
    id: 69,
    reviewer: "Reviewer 3",
    title: "Senior Software Engineer",
    relationship: "coworker",
    date: "10/03/2025",
    text: "Excellent collaboration this week on PAT design - fruitful discussion and answering my questions across several levels, with help me get up to speed and fill in gaps",
    scores: [
      { value: 8, attribute: "Navigated levels of thinking" },
      { value: 8, attribute: "Collaborated effectively" },
    ],
  },
  {
    id: 70,
    reviewer: "Reviewer 3",
    title: "Senior Software Engineer",
    relationship: "coworker",
    date: "10/29/2025",
    text: "Good engagement today in PAT and FDE demos - great to see you on the field answering questions from broad audience. Also had compelling questions for folks presenting in FDE demos.",
    scores: [
      { value: 7, attribute: "Listened well" },
      { value: 7, attribute: "Acted like an owner" },
    ],
  },
  {
    id: 71,
    reviewer: "Reviewer 25",
    title: "Senior Investment Associate",
    relationship: "coworker",
    date: "10/29/2025",
    text: "Good code review comments on my first context PR - helped me learn how to think about context and do the later ones better",
    scores: [{ value: 7, attribute: "Developed others" }],
  },
  {
    id: 72,
    reviewer: "Reviewer 22",
    title: "Architect",
    relationship: "coworker",
    date: "10/29/2025",
    text: `On Pocket Analyst, took ownership in a great way: iterated quickly on architecture, made it easy for the business at appropriate times and clearly, was transparent without letting transparency become too distracting from the work, responsive on needs from others.\n\nI'm very happy with him on the team: Pocket Analyst is ambitious and ambiguous and he is navigating that smoothly, great relief for me personally.\n\nAreas for improvement:\n- It's clear when you are engaged in a discussion, but also clear when you are disengaged. Meetings can be a drain on you — you allowed yourself to fully focus on meeting content and find a way (with meeting RPs/others) to *make* the time more should help make it easier to shape our time together — please do so.\n- Find more ways to bring building blocks back to the community. You are blazing a trail to a hilltop but there are smaller traveled that need more of a nudge from you to lay the path.\n- Reflect more transparently on your process. We used to have retrospectives but given the nature of forward deployed work I'd love to get a crisp understanding from you of how things are going and how you're diagnosing issues in the process.\n- Sometimes you have an idea that you want to pursue despite pushback from others. This can be okay and healthy but I've found that digging deeper into these issues with you find us in a game of semantics because it's like we agree and disagree at the same time but we don't know where the distinction comes from.\n- Get closer to the business content: it's remarkable that you're able to bridge the gap so well but on occasion you'll gloss over a use case. Related to this, sometimes I think you try to answer business questions and it doesn't come as strong and clear — foster that understanding and close that gap.`,
    scores: [
      { value: 9, attribute: "Designed conceptual/practical architecture" },
      { value: 10, attribute: "Delivered results" },
      { value: 5, attribute: "Communicated clearly" },
      { value: 8, attribute: "Collaborated effectively" },
      { value: 10, attribute: "Acted like an owner" },
      { value: 6, attribute: "Diagnosed" },
    ],
    topic: "2025 EOY Reviews",
  },
  {
    id: 73,
    reviewer: "Reviewer 26",
    title: "Senior Software Engineer",
    relationship: "coworker",
    date: "10/29/2025",
    text: "re: sandbox check-in meeting\n\nyou really acted like an owner in driving requirements for sandbox work today. it was an extremely high bandwidth conversation. came out of the meeting with a lot of clarity on what we should be building and how that immediately impacts your work\n\nalso can tell you've built a lot of context in the alpha engine space now and it shows",
    scores: [
      { value: 8, attribute: "Acted like an owner" },
      { value: 9, attribute: "Collaborated effectively" },
      { value: 8, attribute: "Created clarity" },
    ],
  },
  {
    id: 74,
    reviewer: "Very Senior Investment Person",
    title: "Very Senior Investment Person",
    relationship: "manager",
    date: "10/29/2025",
    text: "PAT demo was great. Very exciting to see you all putting this together out of what seem like really important fundamental building blocks that we'll use over and over. In particular, I'm very excited about the 'write everything down in LLM-consumable contexts and learn from it' approach. Also thought you found a good way to address a large volume of on-the-fly questions. Looking forward to seeing this evolve.",
    scores: [
      { value: 8, attribute: "Orchestrated people and processes effectively" },
      { value: 9, attribute: "Shaped change" },
      { value: 8, attribute: "Delivered results" },
    ],
  },
  {
    id: 75,
    reviewer: "Reviewer 27",
    title: "Senior Software Engineer",
    relationship: "coworker",
    date: "10/28/2025",
    text: "Worked with me on code-assist and BOTS.\n\nOverall, great to work with - was the one I remember with the opposing view of how we should do code-assist in order to do things vs pure context. Also greatly improved the code-assist tests\n\non BOTS was great to work with - was good at popping issues - one piece of advice would be to dive into the platform more rather than waiting for enablement",
    scores: [
      { value: 8, attribute: "Designed conceptual/practical architecture" },
      { value: 8, attribute: "Built community" },
      { value: 6, attribute: "Developed infrastructure" },
      { value: 8, attribute: "Understood business requirements" },
    ],
    topic: "2025 EOY Reviews",
  },
  {
    id: 76,
    reviewer: "Santi Weight",
    title: "Senior Software Engineer",
    relationship: "coworker",
    date: "10/28/2025",
    text: `redot w/ topic\n\nabove - 5. Expectations @ L5.\n\n5 is for above the bar delivery and for the large amount of idea generation and clarity i drove across multiple unclear projects with a lack of direction and driving design + clear and aggressive execution. PAT clearest example of this where I've excelled across 4 projects this year, 3 of them being ambiguous projects.\n\nWas holding a wide view of Plaid prior to its shut-down and driving the core problems in the compiler while delivering features, priorities and building/delivering books of work (reworking list handling throughout compiler; function dispatch; fixing optimization frameworks; lambdas etc.)\n\nFinished the swing on pre-filters. built out the BoW and delivered it while managing UATs etc. w/ Jon. Grabbed pre-filters and core issues while taking an uncertain feature into a clear and stable place.\n\nPost-Plaid got thrown into an uncertain authoring team: ideated the Logic Model and drove it to completion and proliferation. become the foundation of many spin-off projects and one of the major arch wins in ST over the past few years. Set the ground for new logical analyses (e.g. new linting rules, the inferred outputtables LSIP + POC). Lastly, the Logic Model took a massive bar to develop now because of the substantive refactors i designed and implemented (e.g. migrating to scala case classes, which simplified rollout). Presented the work and knowledge shared, and now the work stands on its own and has been easy to extend.\n\nCode Assist: jumped into another uncertain world and took it through completion with Eric + Jon. Especially later in the process, getting users motivated to get Code Assist in an excellent state (driving a lot of the Hackathon etc.). threw a ton of energy into new books of work and design. Developed the "toolbox" (your naming may vary) approach and design docs that are now the standard, pushed towards the approach of small incremental design that compounds. Took over testing framework effort that was failing and delivered clarity, delivering 20x speed improvements and vastly simpler stack w/ Cody in ~1 week.\n\nThe work Jon + I did here spun off the business-co-led code assist developer project, where i was guiding IEs across various contexts for delivery: helped Brad design ST migrations which he pushed to the wider community; plethora of code assist contexts. In general, IEs/IAs and helping them build their solutions.\n\nPAT: worked w/ Brendan to define a good goal, and then drove project w/ team through ambiguity on multiple axes: product and tech. Paved the way on new design across a load of axes: high-level tech arch, caching execution of python, LLM code-gen for pandas compilation, agentic frameworks in AE, testing of agents. Product-wise navigated a huge number of ambiguities and made quality calls that have paid off. As of last ~month have also been managing project at the goals and execution level. Project not delivered yet but delivered the CIO Summit, where PAT is becoming part of BW's AI posture. Resulting from the clarity i helped build in PAT, it's now back to Tech (e.g. now one of primary drivers for GitLab, sandboxing, composer vizlets et al).`,
    scores: [{ value: 8, attribute: "Delivered results" }],
    topic: "2025 EOY Reviews",
  },
  {
    id: 77,
    reviewer: "Reviewer 28",
    title: "Product Manager",
    relationship: "coworker",
    date: "10/31/2025",
    text: "Good focus, good clarity, and leaving space for thinking.",
    scores: [
      { value: 9, attribute: "Communicated clearly" },
      { value: 9, attribute: "Thought independently" },
      { value: 8, attribute: "Synthesized the situation" },
    ],
  },
  {
    id: 78,
    reviewer: "Reviewer 4",
    title: "Product Manager",
    relationship: "coworker",
    date: "10/30/2025",
    text: "Impressed at how you react well to feedback and show immediate change in collaboration and communication. Case at hand: last week about how we work together shifted the next day into a meaningfully better way of working together. Thank you.",
    scores: [{ value: 8, attribute: "Improved/Grew" }],
  },
  {
    id: 79,
    reviewer: "Reviewer 29",
    title: "Contingent Worker",
    relationship: "report",
    date: "11/10/2025",
    text: "Lead the team very effectively. And it was pleasure working with you. Learnt a lot from you.",
    scores: [
      { value: 10, attribute: "Listened well" },
      { value: 10, attribute: "Cared for others" },
    ],
  },
  {
    id: 80,
    reviewer: "Santi Weight",
    title: "Senior Software Engineer",
    relationship: "coworker",
    date: "11/01/2025",
    text: `This week was tough. Came off a hard drive to execute for CIO Summit after a long 3 months + got sick, and I faltered.\n\nUp until now, I've purposefully kept PAT siloed to keep thought clarity and clean execution. I didn't effectively anticipate what the level of clarity is going to need to be for PAT to land bigly and (2) not being communicated to the people who feel they need it. I've been thinking small.\n\nFor curious readers: I'm tackling first-class and expect much more clarity over next day or two.\n\nGiving myself some grace because this is new for me, but... I was mentally complacent and was riding the ego high of having built something that people like PAT, the time for feeling good about is coming to pass, and it's time to be cut-throat again.\n\nOne big failing here is that I've been stuck on having full ownership over the tech design. I need to open it up and get help and experience here and make sure I'm not missing things (my lack of rigor+experience here is obvious based on Lore's reco).\n\nNow that PAT is changing, I need to be less hands-on with some things and more hand-off with others. The scale of things changing is a combo of an unexpected happy outcome, but also some lack of forward-thinking.`,
    scores: [
      { value: 4, attribute: "Strategized" },
      { value: 4, attribute: "Knew what you didn't know and what to do about it" },
      { value: 4, attribute: "Handled pressure" },
    ],
  },
  {
    id: 81,
    reviewer: "Reviewer 30",
    title: "Senior Software Engineer",
    relationship: "coworker",
    date: "11/18/2025",
    text: "Super helpful to chat with you today. Definitely I am struck by your fierce focus on momentum and objectivity identifying what matters most. I felt very heard when we got to the kernel of what Sandbox is really solving, and likewise it was helpful for me for you to clarify where in PAT those concerns do and do not apply. Great collaboration.",
    scores: [
      { value: 8, attribute: "Managed risk" },
      { value: 8, attribute: "Designed conceptual/practical architecture" },
      { value: 8, attribute: "Disagreed productively" },
    ],
  },
  {
    id: 82,
    reviewer: "Reviewer 3",
    title: "Senior Software Engineer",
    relationship: "coworker",
    date: "11/14/2025",
    text: "Listening well and probing to understand my feedback for tightening work tracking (tickets, MRs, sharing context more, reducing overhead solution.\n\nConstructively (as we discussed a bit live) as TL you would benefit from proactively assessing level of context for folks involved. Make sure handoffs and asks are clear. Evident for external partners, but also for internal folks because we don't / won't be working in the same work areas to the degree we did a few weeks ago.",
    scores: [
      { value: 8, attribute: "Listened well" },
      { value: 5, attribute: "Created clarity" },
    ],
  },
  {
    id: 83,
    reviewer: "Reviewer 4",
    title: "Product Manager",
    relationship: "coworker",
    date: "01/15/2026",
    text: "Noticed a positive upwards trend in your collaboration with others in the recent period. Pulling on others for feedback along the way, and pushing more on providing transparency (e.g. GA thoughts) with senior tech leadership ahead of time and well communicated.",
    scores: [{ value: 9, attribute: "Collaborated effectively" }],
  },
  {
    id: 84,
    reviewer: "Santi Weight",
    title: "Senior Software Engineer",
    relationship: "coworker",
    date: "01/16/2026",
    text: "being a little weasily in pat retro re. pixi stuff",
    scores: [{ value: 5, attribute: "Welcomed feedback" }],
  },
  {
    id: 85,
    reviewer: "Reviewer 1",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "01/08/2026",
    text: "really, really excellent work getting PAT to where it is today. I know we haven't launched (just) yet, but you should all be incredibly proud.",
    scores: [{ value: 9, attribute: "Delivered results" }],
  },
  {
    id: 86,
    reviewer: "Reviewer 1",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "01/07/2026",
    text: "always willing to get your thoughts out there and give feedback. such a great partner. thank you",
    scores: [
      { value: 8, attribute: "Collaborated effectively" },
      { value: 8, attribute: "Disagreed productively" },
    ],
  },
  {
    id: 87,
    reviewer: "Reviewer 31",
    title: "Senior Product Manager",
    relationship: "coworker",
    date: "07/18/2025",
    text: "Congrats on the Code Assist GA release. It's really a game changer, one which honestly has significantly exceeded what we knew it could help our investors, but you and the team have turned it into something that's become the poster child of what we can do. You've created so much excitement and goodwill along the way. Thank you.",
    scores: [
      { value: 8, attribute: "Delivered results" },
      { value: 8, attribute: "Displayed skill & experience" },
      { value: 8, attribute: "Was creative" },
    ],
  },
  {
    id: 88,
    reviewer: "Reviewer 1",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "07/14/2025",
    text: "After just a few meetings on the AI analyst project with you today, overwhelmingly excited to be working on this with you, delivering tons of impact.",
    scores: [{ value: 9, attribute: "Collaborated effectively" }],
  },
  {
    id: 89,
    reviewer: "Reviewer 32",
    title: "Investment Associate",
    relationship: "coworker",
    date: "07/10/2025",
    text: "I think you guys have done a really good job being understanding of the challenge in setting aside time to help with our work but also making sure the ball keeps rolling. Makes you great to work with.",
    scores: [{ value: 9, attribute: "Collaborated effectively" }],
  },
  {
    id: 90,
    reviewer: "Reviewer 1",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "07/10/2025",
    text: "Excellent Tableness-like Python spike. Both the initiative and the swing. Really great energy here.\n\nAlso thought you were good at bringing the AI code assist discussion to a higher level in the meeting today.",
    scores: [
      { value: 9, attribute: "Took the bull by the horns" },
      { value: 8, attribute: "Navigated levels of thinking" },
    ],
  },
  {
    id: 91,
    reviewer: "Reviewer 8",
    title: "Engineering Manager",
    relationship: "manager",
    date: "06/27/2025",
    text: "#ManagerReview\nMid-Year - Above\n\nHas had a pretty solid first half of the year. Strong contributions on the logic model and a good start in the AI space. Have watched him go from behind the scenes to take a leading role in driving the code assist hackathon, helping colleagues and push ethos of AI assist authoring. The logic model was a proposal thought through fairly independently that is now helping bridge a few different gaps. I think what needs to be worked on is how to process and deal with conflicts, friction and out-of-syncness effectively. Gets frustrated, tends to carry a synthesis in his head at time without testing it out, which can lead to a bit of long-winded conversations and distress. For him to make more impact - especially in this high paced, changing environment - needs to learn how to give his teammates more grace, be more explicit and not get easily flustered / frustrated.",
    scores: [
      { value: 8, attribute: "Delivered results" },
      { value: 8, attribute: "Took the bull by the horns" },
      { value: 8, attribute: "Thought independently" },
      { value: 4, attribute: "Disagreed productively" },
      { value: 5, attribute: "Collaborated effectively" },
      { value: 8, attribute: "Designed conceptual/practical architecture" },
    ],
    topic: "Technology Mid-Year Reviews 2025",
  },
  {
    id: 92,
    reviewer: "Reviewer 1",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "08/06/2025",
    text: "Pretty instrumental to this AI analyst push. Great thoughts on design as well as on execution. Finding your strategic instinct valuable as well.",
    scores: [
      { value: 8, attribute: "Collaborated effectively" },
      { value: 8, attribute: "Strategized" },
    ],
  },
  {
    id: 93,
    reviewer: "Reviewer 8",
    title: "Engineering Manager",
    relationship: "manager",
    date: "08/05/2025",
    text: "I find it hard to sync and to stay in sync with you. You often jump to conclusions and then stick to them in a way that I find consuming, I just don't expect this from engineers at your belt on my team. The latest is the belting conversation over...",
    scores: [{ value: 3, attribute: "Listened well" }],
  },
  {
    id: 94,
    reviewer: "Reviewer 2",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "07/30/2025",
    text: "Good stuff today. Excited to be tackling this problem with you all",
    scores: [{ value: 8, attribute: "Strategized" }],
  },
  {
    id: 95,
    reviewer: "Reviewer 1",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "07/30/2025",
    text: "Good design for gen, execute, schema for AI analyst",
    scores: [{ value: 8, attribute: "Designed conceptual/practical architecture" }],
  },
  {
    id: 96,
    reviewer: "Reviewer 1",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "07/29/2025",
    text: "Appreciate your feedback -- keep this coming. Thank you. Hopefully a good clarifying working session for both of us this morning.",
    scores: [
      { value: 8, attribute: "Was bluntly honest" },
      { value: 8, attribute: "Welcomed feedback" },
    ],
  },
  {
    id: 97,
    reviewer: "Reviewer 33",
    title: "Software Engineer",
    relationship: "coworker",
    date: "07/24/2025",
    text: "introducing me so i could put faces to names",
    scores: [{ value: 8, attribute: "Built community" }],
  },
  {
    id: 98,
    reviewer: "Reviewer 34",
    title: "Very Senior Tech Person",
    relationship: "manager",
    date: "07/23/2025",
    text: "I thought your ribbing at Armaan when you got on the microphone in front of the entire company missed the mark by 20%.",
    scores: [{ value: 4, attribute: "Built community" }],
  },
  {
    id: 99,
    reviewer: "Reviewer 31",
    title: "Senior Product Manager",
    relationship: "coworker",
    date: "09/14/2025",
    text: "Pretty impressive demo of Pat. Looks like you've accomplished a lot, including a lot of good fast loops/pivots, in a short time (having metrics), the dash UI experiments, the multiple pivots on the agent architecture itself.\n\nAnd it was a tight demo — brought the room through it well, anticipated questions, good timing.",
    scores: [
      { value: 8, attribute: "Delivered results" },
      { value: 8, attribute: "Synthesized the situation" },
      { value: 8, attribute: "Collaborated effectively" },
    ],
  },
  {
    id: 100,
    reviewer: "Reviewer 35",
    title: "Senior Product Manager",
    relationship: "coworker",
    date: "09/12/2025",
    text: "PaT demo for tech. Great walk through not just of product to date, but learnings to get here, paths discarded along the way.",
    scores: [
      { value: 8, attribute: "Created clarity" },
      { value: 8, attribute: "Was organized and reliable" },
    ],
  },
  {
    id: 101,
    reviewer: "Reviewer 22",
    title: "Architect",
    relationship: "coworker",
    date: "09/11/2025",
    text: "Presentation on Pocket Analyst was very well-organized: telling the story and navigating levels of detail and demonstrating the product.",
    scores: [
      { value: 9, attribute: "Built the path to the vision" },
      { value: 9, attribute: "Communicated clearly" },
    ],
  },
  {
    id: 102,
    reviewer: "Reviewer 36",
    title: "Senior Software Engineer",
    relationship: "coworker",
    date: "09/10/2025",
    text: "Good, assertive, off-the cuff thoughts on how product limits should hit users in Hydra, during realtime post-mortem.",
    scores: [{ value: 7, attribute: "Designed conceptual/practical architecture" }],
  },
  {
    id: 103,
    reviewer: "Reviewer 37",
    title: "Software Engineer",
    relationship: "coworker",
    date: "09/08/2025",
    text: "Lunch dot - I think you're right that it's not ideal in the long term and would build more community to eat together.",
    scores: [
      { value: 8, attribute: "Built community" },
      { value: 8, attribute: "Gave useful feedback" },
    ],
  },
  {
    id: 104,
    reviewer: "Reviewer 38",
    title: "Very Senior Investment Person",
    relationship: "manager",
    date: "09/05/2025",
    text: "I am wary of my bias to be overly bullish on Pat the pocket analyst (and possibly for you to all to be excited enough to be a bit biased as well) -- but in my view you all are doing a great job. Would get more skeptical voices from AIA to tear at it even before our beta testers do — but the importance of standing up the benchmarking looks good. Strategic thinking good as far as I can tell, particularly on the importance of how important you are. All add up to pushing the distribution of outcomes further to the right by both raising the floor and raising the upside for how this can scale. Feels like I am watching a special effort come together with really high quality data) even if it falls short of our hopes.",
    scores: [
      { value: 8, attribute: "Strategized" },
      { value: 8, attribute: "Used strong logic" },
    ],
  },
  {
    id: 105,
    reviewer: "Reviewer 2",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "09/03/2025",
    text: "You've been crushing things recently -- esp the various bugs we've been running into and the broader architecture thread. Always very much so enjoy the process in which you've been doing all this stuff recently (collaborative, open minded). Always willing to listen, unblocked, and generally just fun to work with",
    scores: [
      { value: 8, attribute: "Developed infrastructure" },
      { value: 8, attribute: "Designed conceptual/practical architecture" },
      { value: 8, attribute: "Used strong logic" },
    ],
  },
  {
    id: 106,
    reviewer: "Reviewer 1",
    title: "Senior Investment Associate",
    relationship: "manager",
    date: "09/03/2025",
    text: "Two things at two levels for PAT. Great collaboration, architecture, delivery, and troubleshooting.",
    scores: [
      { value: 9, attribute: "Collaborated effectively" },
      { value: 9, attribute: "Designed conceptual/practical architecture" },
      { value: 9, attribute: "Delivered results" },
      { value: 9, attribute: "Troubleshot effectively" },
    ],
  },
  {
    id: 107,
    reviewer: "Reviewer 4",
    title: "Product Manager",
    relationship: "coworker",
    date: "08/22/2025",
    text: "A few good things I saw today in our engagement. Listening well and developing others.",
    scores: [
      { value: 8, attribute: "Listened well" },
      { value: 8, attribute: "Developed others" },
    ],
  },
  {
    id: 108,
    reviewer: "Reviewer 34",
    title: "Very Senior Tech Person",
    relationship: "manager",
    date: "08/22/2025",
    text: "Loved getting to see you demo your work earlier this week. Great courage in presenting and solid code delivery.",
    scores: [
      { value: 8, attribute: "Displayed courage" },
      { value: 8, attribute: "Developed code" },
      { value: 5, attribute: "Navigated levels of thinking" },
    ],
  },
];
